name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run smoke tests
      run: bash run_tests.sh
  test-stack:
    strategy:
      matrix:
        stack: [heroku-20]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run stack test
      run: bash test/stack-test.sh ${{ matrix.stack }} >> $GITHUB_STEP_SUMMARY
      env:
        TAILSCALE_TEST_AUTH_KEY: ${{ secrets.TAILSCALE_TEST_AUTH_KEY }}
